scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 1000

# Font configuration
font:
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: HackNerd Font
    style: Italic
  size: 6.0

unfocused_hollow: true

background_opacity: 0.90

cursor:
  #   - â–‡ Block
  #   - _ Underline
  #   - | Beam
  style: Block

mouse:
 hide_when_typing: true



 #Colors (Dracula)
 #colors:
 #  # Default colors
 #  primary:
 #    background: '#282a36'
 #    foreground: '#f8f8f2'
 #
 #  # Normal colors
 #  normal:
 #    black:   '#000000'
 #    red:     '#ff5555'
 #    green:   '#50fa7b'
 #    yellow:  '#f1fa8c'
 #    blue:    '#caa9fa'
 #    magenta: '#ff79c6'
 #    cyan:    '#8be9fd'
 #    white:   '#bfbfbf'
 #
 #  # Bright colors
 #  bright:
 #    black:   '#575b70'
 #    red:     '#ff6e67'
 #    green:   '#5af78e'
 #    yellow:  '#f4f99d'
 #    blue:    '#caa9fa'
 #    magenta: '#ff92d0'
 #    cyan:    '#9aedfe'
 #    white:   '#e6e6e6'
key_bindings:
  - { key: K,   mods: Alt,           action: ScrollLineUp }
  - { key: J,   mods: Alt,           action: ScrollLineDown }
# # hite:   '#f1f1f1'
# # Colors (Oceanic Next)
#colors:
#  # Default colors
#  primary:
#    background: '#1b2b34'
#    foreground: '#d8dee9'
#
#  # Colors the cursor will use if `custom_cursor_colors` is true
#  cursor:
#    text: '#1b2b34'
#    cursor: '#ffffff'
#
#  # Normal colors
#  normal:
#    black:   '#343d46'
#    red:     '#EC5f67'
#    green:   '#99C794'
#    yellow:  '#FAC863'
#    blue:    '#6699cc'
#    magenta: '#c594c5'
#    cyan:    '#5fb3b3'
#    white:   '#d8dee9'
#
#  # Bright colors
#  bright:
#    black:   '#343d46'
#    red:     '#EC5f67'
#    green:   '#99C794'
#    yellow:  '#FAC863'
#    blue:    '#6699cc'
#    magenta: '#c594c5'
#    cyan:    '#5fb3b3'
#    white:   '#d8dee9'
# Colors (Gruvbox light)
# # Colors (Gruvbox dark)
# # Colors (Hyper)
# # Colors (Ayu Mirage)
colors:
  # Default colors
  primary:
    background: '#202734'
    foreground: '#CBCCC6'

  # Normal colors
  normal:
    black: '#191E2A'
    red: '#FF3333'
    green: '#BAE67E'
    yellow: '#FFA759'
    blue: '#73D0FF'
    magenta: '#FFD580'
    cyan: '#95E6CB'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F27983'
    green: '#A6CC70'
    yellow: '#FFCC66'
    blue: '#5CCFE6'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'
